// First matching keyword wins, so list specific words before general ones.
const RULES: [RegExp, string][] = [
  [/no school/i, '🏖️'],
  [/muffin/i, '🧁'],
  [/cereal bar/i, '🍫'],
  [/cereal/i, '🥣'],
  [/hot breakfast/i, '🍳'],
  [/breakfast bread/i, '🍞'],
  [/pizza|crunchers/i, '🍕'],
  [/burger/i, '🍔'],
  [/hot dog|frank/i, '🌭'],
  [/taco/i, '🌮'],
  [/nacho/i, '🧀'],
  [/lasagna|spaghetti|penne|alfredo/i, '🍝'],
  [/mac(aroni)?/i, '🧀'],
  [/dumpling/i, '🥟'],
  [/chicken/i, '🍗'],
  [/sub|sandwich/i, '🥪'],
  [/french toast/i, '🍞'],
  [/breadstick|roll|bun|bread/i, '🥖'],
  [/rice/i, '🍚'],
  [/sausage/i, '🌭'],
  [/hash brown|potato|tater/i, '🥔'],
  [/corn/i, '🌽'],
  [/broccoli/i, '🥦'],
  [/carrot/i, '🥕'],
  [/cucumber/i, '🥒'],
  [/pepper/i, '🫑'],
  [/pea|green bean|bean/i, '🫛'],
  [/celery|salad|romaine/i, '🥗'],
  [/tomato/i, '🍅'],
  [/green apple/i, '🍏'],
  [/apple/i, '🍎'],
  [/orange/i, '🍊'],
  [/banana/i, '🍌'],
  [/raisin/i, '🍇'],
  [/juice/i, '🧃'],
  [/fruit/i, '🍓'],
  [/snack/i, '🥨'],
  [/milk/i, '🥛'],
];

export function foodEmoji(name: string): string {
  return RULES.find(([pattern]) => pattern.test(name))?.[1] ?? '🍽️';
}
